/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CreateProjectDto = {
  isActive?: boolean;
  name: string;
  slug: string;
  logoUrl: string;
};

export type User = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  isCensored: boolean;
  isActive: boolean;
  uid: string;
  accountType: string;
  roles: string[];
  username: string;
  nearWalletAccountId: string;
};

export type Project = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  isCensored: boolean;
  isActive: boolean;
  name: string;
  slug: string;
  logoUrl: string;
  owner: User;
};

export type UpdateProjectDto = {};

export type NearLoginDto = {
  username: string;
  signedJsonString: string;
};

export type NearLoginResponse = {
  token: string;
};

export type CreateUserDto = {};

export type UpdateUserDto = {};
