/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type PaginatedDto = {
  total: number;
  limit: number;
  offset: number;
};

export type CreateProjectDto = {
  name: string;
  slug: string;
  logoUrl: string;
};

export type User = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  isCensored: boolean;
  isActive: boolean;
  uid: string;
  accountType: string;
  roles: string[];
  username: string;
  nearWalletAccountId: string;
};

export type Project = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  name: string;
  slug: string;
  logoUrl: string;
  owner: User;
};

export type UpdateProjectDto = {
  name?: string;
  slug?: string;
  logoUrl?: string;
};

export type NearLoginRequestDto = {
  username: string;
  signedJsonString: string;
};

export type NearLoginResponseDto = {
  token: string;
};

export type CreateAddressDto = {
  wallet: string;
  alias: string;
  email?: string;
  phone?: string;
};

export type Address = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  wallet: string;
  alias: string;
  phone: string;
  email: string;
  owner: User;
};

export type UpdateAddressDto = {
  email?: string;
  phone?: string;
};

export type CreatePaymentDto = {
  uid: string;
  memo: string;
  amount: string;
  receiver: string;
  receiver_fungible: string;
};

export type Payment = {
  /**
   * @format date-time
   */
  updatedAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  uid: string;
  memo: string;
  amount: string;
  receiver: string;
  receiver_fungible: string;
  status: "pending" | "paid";
  owner: User;
};

export type PaymentDto = {
  _id: string;
  uid: string;
  amount: string;
  memo: string;
  receiver: string;
  receiver_fungible: string;
  status: "pending" | "paid";
};
